### ISSUE TITLE
"No BINSTAR_TOKEN present" on Travis

### ISSUE THREAD

**Issue by frol** [conda-forge/nuitka-feedstock#8]
@jakirkham Mac OS build [succeeds](https://travis-ci.org/conda-forge/nuitka-feedstock/jobs/184587844), but doesn't get published due to missing secret keys:

```
$ upload_or_check_non_existence ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
No BINSTAR_TOKEN present, so no upload is taking place. The distribution just built is not already available on conda-forge's main channel.
```

**Comment by jakirkham** [comment]
On the PR from a fork secure environment variables are not set. They are only set on builds of branches on this feedstock (e.g. after merge). This is expected behavior. It appears things are getting published fine AFAICT.

![screen shot 2016-12-16 at 14 14 39](https://cloud.githubusercontent.com/assets/3019665/21275308/327f72a4-c39a-11e6-896c-8a50dabc44e4.png)

**Comment by jakirkham** [comment]
On the PR from a fork secure environment variables are not set. They are only set on builds of branches on this feedstock (e.g. after merge). This is expected behavior. It appears things are getting published fine AFAICT.

![screen shot 2016-12-16 at 14 17 38](https://cloud.githubusercontent.com/assets/3019665/21275366/7250e3ea-c39a-11e6-8aa5-d452159a5586.png)

**Comment by frol** [comment]
I beg your pardon, I believe I was looking in a wrong place or something was glitching and presented me wrong info.
